### ISSUE TITLE
res is just being passed instead of actually returned in callbacks

### ISSUE THREAD

**Issue by tkgalk** [thebearingedge/express-unit#7]
```AssertionError: expected { Object (app, locals, ...) } to equal 422```
or
``` expected [Function] to equal 422```
etc.

When trying to:

```
            const setup = spy((req, res, next) => {
                // setting headers
                next();
            });

            run(setup, checkIfSubmitted, (err, req, res) => {
                expect(res).to.have.status(422);
                done();
            });
```

I have tried those assertions: `expect(res).to.have.status(422);`, `expect(res.status).to.be.equal(422)`, `expect(res.status()).to.be.equal(422)`, etc.

Anything I am missing? The middlware is simple:

```
export function checkIfSubmitted(req, res, next) {
    return res.status(422).json({'test': 'test'});
}
```

Basically - it gets the original res in the callback. The middleware gets called from test (I can console.log from it) and if I run it through Postman - it successfully sets 422.

**Comment by thebearingedge** [comment]
Hi, Thanks for opening this issue.

> res is just being passed instead of actually returned

This is the intended behavior of `express-unit`. This is how I would test your middleware, using `sinon-chai`.

```js
const setup = (req, res, next) => {
  req.headers['x-test-header'] = 'Something'
  spy(res, 'status')
  spy(res, 'json')
  next()
}

run(setup, checkIfSubmitted, (err, req, res) => {
  expect(err).to.be.null
  expect(res.status).to.have.been.calledWith(422)
  expect(res.json).to.have.been.called
})
```

If this test passes, then you know that your middleware does the correct thing when it sees the header. `res` is just passed so you can check the method calls or headers after the middleware runs. It might help to think of your assertion callback as a last middlware in the `setup` -> `middleware` -> `assertions` stack.

Does this help?
