### ISSUE TITLE
Object/calledNext Proposal

### ISSUE THREAD

**Issue by h-cow** [thebearingedge/express-unit#8]
# Object/calledNext Proposal

### Note
I might just be going about this the wrong way. If this seems logical to you I would like to send you a pull request with the changes.
I suppose if I make my errors JSON strings I wouldn't care about ```calledNext``` which might be a better route.

### Proposal
1. Return an object instead of an array
2. Return a "calledNext" boolean

#### For "Tests Example 1"
- One less line of code for every route that calls ```res.sendStatus```
#### For "Tests Example 2"
- As ugly as ```(await result()).err``` is its more readable then ```(await result())[0]```
  - This code might be ugly enough to justify never writing it in the first place.

### Negatives
- Brakes the **ENTIRE** API
- calledNext will make no sense in synchronouse use of the library and would be a false flag.
  - I think it would have to omit calledNext if called in a none promise form.

## Code that needs the test
```
const userWithId = users => wrap(async ({ body: {id} }, res, next) => {
  const exists = await users.isId(id)
  if (!exists) return res.sendStatus(400)
  next()
})
```
I was messing around with explicit descriptions and minimal code so there is 2 different styles here but all the example do the same 3 tests

### Current
```
context('when the user is found', () => {
  it(`advanced to the next middleware`, async () => {
    const setup = (req, res, next) => {
      req.body.id = 5
      res.sendStatus = stub()
      stub(users, 'isId').returns(Promise.resolve(true))
      next()
    }
    const [ err, , res ] = await run(setup, middleware)
    expect(err).to.equal(null)
    expect(res.sendStatus.called).to.equal(false)
    expect(users.isId).to.have.been.calledWith(5)
  })
})
```
### Proposed
```
// Perposal Example with shorter less explicit
context('when the user is found', () => {
  it(`advanced to the next middleware`, async () => {
    const setup = (req, res, next) => {
      req.body.id = 5
      stub(users, 'isId').returns(Promise.resolve(true))
      next()
    }
    const { err, res, calledNext } = await run(setup, middleware)
    expect(err).to.equal(null)
    expect(calledNext).to.equal(true)
    expect(users.isId).to.have.been.calledWith(5)
  })
})
```

### Current
```
context('when the user is found', () => {
  const setup = (req, res, next) => {
    req.body.id = 5
    stub(users, 'isId').returns(Promise.resolve(true))
    next()
  }
  const result = () => run(setup, middleware)

  it('calls next middleware', (done) => { run(setup, middleware, done) })
  it(`doesn't error out`, async() => {
    expect( (await result())[0] ).to.equal(null)
  })
  it(`calls users.isId`, async () => {
    await result()
    expect(users.isId).to.have.been.calledWith(5)
  })
})
```
### Proposed
```
context('when the user is found', () => {
  const setup = (req, res, next) => {
    req.body.id = 5
    stub(users, 'isId').returns(Promise.resolve(true))
    next()
  }
  const result = () => run(setup, middleware)

  it('calls next middleware', (done) => { run(setup, middleware, done) })
  it(`doesn't error out`, async() => {
    expect( (await result()).err ).to.equal(null)
  })
  it(`calls users.isId`, async () => {
    await result()
    expect(users.isId).to.have.been.calledWith(5)
  })
})
```

**Comment by thebearingedge** [comment]
I think you are trying to DRY up your tests too much. In general AAA is a good pattern for tests (Arrange, Act, Assert). Multiple assertions aren't too bad if you stick to a single action.

```js
context('when the user is found', () => {
  // Arrange
  const setup = (req, res, next) => {
    req.body.id = 5
    res.sendStatus = stub()
    stub(users, 'isId').returns(Promise.resolve(true))
    next()
  }
  it('advances to the next middleware', async () => {
    // Act
    const [ err, , res ] = await run(setup, middleware)
    // Assert
    expect(err).to.equal(null) // No error passed to `next`
    expect(users.isId).to.have.been.calledWith(5) // Correctly checked `isId`
    expect(res.sendStatus.called).to.equal(false) // No response sent
  })
})

context('when the user is not found', () => { /* AAA */ })
```

Regarding your example unit, I recommend `throw`ing an error in async middleware instead of sending a response. Let your error handler send the response. Then you can assert that the right error was thrown. Or pass it to `next` for the same effect.

```js
const userWithId = users => wrap(async ({ body: {id} }, res, next) => {
  const exists = await users.isId(id)
  if (!exists) throw new Unauthorized()
  next()
})

// In test

it('throws an Unauthorized error', async () => {
  const [ err ] = await run(setup, middleware)
  expect(err).to.be.an.instanceOf(Unauthorized) 
})
```

**Comment by h-cow** [comment]
1, Got it, also I don't always follow AAA. Example: I may have a callback in "Arrange" that does A "Assert" inside. should I move "Assert" to a function after "Act" to keep it AAA.
2. Your Amazing throwing an error makes a lot of sense in this situation. I can customize the response later via middleware and the test is tiny.

This was very helpful thanks!

**Comment by h-cow** [comment]
Regarding the last post I found simply assigning a var and via closure getting info on the (spy, stub, mock) and then testing your assumptions after "Act" is a simple way to move the "Assert". Assuming you are using "await" on the "Act". Thanks again!

**Comment by thebearingedge** [comment]
Cool, glad you got a flow you like.
